version: 1
platform_server:
  port: 8085
assets:
  type: file
  value: /home/dev.assets.yaml
data:
  type: postgres
  server: db
  database: platform
  flyway_enabled: true
sep24:
  interactive_url:
    base_url: "http://10.0.2.2:8080/sep24"
  more_info_url:
    base_url: "http://10.0.2.2:8080/sep24/info"
