items:
- id: stellar:USDC:GBDCIPVATEVRFJM5IPOLET6GM3CKMUCE27RSRO67EEZ6VTV4EBG4A5JZ
  distribution_account: GBXNUYF3J6LCYBC33CKDDJUPRSVEURKTGGP2CBSV6JNTP7BU766UMAX7
  significant_decimals: 2
  sep24:
    enabled: true
    deposit:
      enabled: true
      min_amount: 0
      max_amount: 100000
      methods:
      - SEPA
      - SWIFT
    withdraw:
      enabled: true
      min_amount: 0
      max_amount: 100000
      methods:
      - bank_account
      - cash
  sep31:
    enabled: false

- id: iso4217:USD
  significant_decimals: 2
  sep31:
    enabled: false

- id: iso4217:ZMW
  significant_decimals: 2
  sep31:
    enabled: false

clients: []
